baseURL = "https://example.com"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "Purple"
theme = "cayman-hugo-theme"

# Syntax highlighting
pygmentsCodefences = true
pygmentsStyle = "pygments"

# Goldmark has bug on bold/italics so we use blackfriday
[markup]
  defaultMarkdownHandler = "blackfriday"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[params]
  # Header text, can be markdown
  project_name = "Purple"
  project_tagline = "Purple 小组成立于 2015 年 10 月，……"

  # Date format for post list and single pages
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "2006-01-02"

  # Footer text, can be markdown
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."

  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#9b4dca"
  header_background_color_secondary = "#683c9c"

  # Text colors
  section_headings_color = "#303638"
  body_text_color = "#606c71"
  body_link_color = "#9b4dca"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3ecfa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"

[menu]
  [[menu.nav]]
    name = "文章"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "标签"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "关于"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
